### ISSUE TITLE
low load fill and missing items

### ISSUE THREAD

**Issue by zxdev** [irfansharif/cfilter#11]
The paper suggests it is possible to obtain 95% fill. However the current hash methodology I think is the problem with bucket distrobution. 

How to confirm/reproduce the issue.

Generate 100MM random data records and write these to a file using following method.

```
func generate() func() []byte {
	size:=8
	return func() []byte {	
		bytes := make([]byte,size,size)
		for i :=range bytes {
			bytes[i] = byte(rand.Intn(255))
		}
		return bytes
	}
}

func main() {
	next := generate()
	mf,_:= os.Create("./dgen")
	defer mf.Close()
	out:=bufio.NewWriter(mf)
	for i:=0;i<100000000;i++ {
		out.WriteString(hex.EncodeToString(next())+"\n")
	}
	out.Flush()
}
```
The resulting file should be 1.7GB and then confirm they all are unique with 
$ uniq -u dgen dgen2

-rw-r--r--   1 mac  staff  1700000000 Jan  5 14:55 dgen
-rw-r--r--   1 mac  staff  1700000000 Jan  5 15:31 dgen2

Use this 100MM randomized data as the source file, then run the following code.

```
func main() {
	cf := cfilter.New(cfilter.FingerprintSize(8), cfilter.BucketSize(4), cfilter.Size(35000000))
	f, _ := os.Open("dgen")
	defer f.Close()
	scanner := bufio.NewScanner(f)
	i := 0
	t0 := time.Now()
	for scanner.Scan() {
		i++
		st := scanner.Text()
		if chk:= cf.Lookup([]byte(st)); !chk {
			if chk := cf.Insert([]byte(st)); !chk { 
				fmt.Println(i,st,"stuffed")
				break
			}				
			} else {
				fmt.Println(i,st,"exists")
			}
		}
	fmt.Println(time.Since(t0), cf.Count(), float64(cf.Count()) / float64(time.Since(t0).Seconds()))
	f2, _ := os.Open("dgen")
	defer f2.Close()
	scanner2 := bufio.NewScanner(f2)
	i2 := 0
	missing := 0
	t1 := time.Now()
	for scanner2.Scan() {
		i2++
		st := scanner2.Text()
		chk := cf.Lookup([]byte(st))
		if !chk {
			//fmt.Println(i2, st, "missing")
			missing++
		}
	}
	fmt.Println(time.Since(t1), i2, float64(i2) / float64(time.Since(t1).Seconds()),missing)
}

```

Based on the paper, it should be able to handle 95% fill. 100MM into 120MM is only 83.33% filled, so it *should* be fine, however running this crashes 50,895,993

> 
50895993 7cae124e8473d992 stuffed

Now change the parameters to the following to give it tons of room.

```
cf := cfilter.New(cfilter.FingerprintSize(8), cfilter.BucketSize(8), cfilter.Size(20000000))
```

This time it will complete the inserts without getting overstuffed (only 62.5% full), however we have a new problem. There are 5162 missing when we try to do a lookup on them.

$ go run cf.go
3m14.974607833s 100000000 512887.29832959676
1m44.974537314s 100000000 952611.959256893 **5162**

in fingerprint.go, commenting out line 20-22 to account for hashes that hashed to zero some how

```
	/*if fp == nil {
		fp[0] += 7
	}*/
```
 and run again shows that we are still missing 5162

3m16.405886172s 100000000 509149.7095800179
1m39.876159299s 100000000 1.0012399394257959e+06 **5162**

So I think there are two issues.

1) The hashfp() doesn't distribute to the buckets randomly enough since the paper talks about "Empirically, a filter containing up to 4 billion items can effectively fill its hash table with loads of 95% when each bucket holds four fingerprints that are 6 bits or larger." The hashfp() is the only thing I can think of adjusting that could have an impact and allow 95% load. I'm only testing with 100 million samples and can not achieve > 50% load with the current design.

2) What happened to the 5162 that were inserted but can't be found with a subsequent lookup?

Any ideas?

**Comment by zxdev** [comment]
The loss has to do with movements after the initial insert as far as I can tell and I have left off the zero hash rectification off for now.

$ go run cf.go
100000000 2m28.759225861s 672227.2135095439 0
10000001 6.898372635s 1.449617333316257e+06 12

The "lost" 12 with this configuration are found immediately after placement, but not after the full 100MM set completes. I could drop their fingerprints out and then go locate them to verify they are still in the table, but if they are, then the issue will be with how the movement occurs. 

Also, in the code below,I have added a generated image to visually display hash placement in the field.

```
func main() {
	cf := cfilter.New(cfilter.FingerprintSize(8), cfilter.BucketSize(4), cfilter.Size(60000000))
	t0 := time.Now()
	i := 0
	f, _ := os.Open("data/dgen")
	defer f.Close()
	missing1 := 0
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		i++
		st := scanner.Text()
		if chk := cf.Lookup([]byte(st)); !chk {
			if chk := cf.Insert([]byte(st)); !chk {
				fmt.Println(i, st, "stuffed")
				break
			}
			if chk := cf.Lookup([]byte(st)); !chk {
				//fmt.Println(i, st, "not found")
				missing1++
			}
		} else {
			fmt.Println(i, st, "exists")
			break
		}
		//if i > 10000000 {
		//	break
		//}
	}

	cf.Img(12000, 12000) // visualize hash placement 4x60MM container

	fmt.Println(i, time.Since(t0), float64(i)/time.Since(t0).Seconds(), missing1)
	time.Sleep(time.Second * 5)

	f2, _ := os.Open("data/dgen")
	defer f2.Close()

	scanner2 := bufio.NewScanner(f2)
	i2 := 0
	t3 := time.Now()
	missing := 0
	for scanner2.Scan() {
		i2++
		st := scanner2.Text()
		if chk := cf.Lookup([]byte(st)); !chk {
			//fmt.Println(i2, st, "missing")
			missing++
			//break
		}

		if i2 > 10000000 {
			break
		}
	}
	fmt.Println()
	//fmt.Println(cf.Stats())
	fmt.Println(i2, time.Since(t3), float64(i2)/time.Since(t3).Seconds(), missing)

}
```

```
func (cf *CFilter) Img(x1, y1 int) {
	myimage := image.NewRGBA(image.Rectangle{image.Point{0, 0}, image.Point{x1, y1}})
	var row uint
	row = 0
	bk := uint8(0)
	for x := 0; x < x1; x++ {
		for y := 0; y < y1; y++ {
			elm := cf.buckets[row][bk]
			bk++
			if bk > uint8(len(cf.buckets[row])-1) {
				bk = 0
				row++
			}
			n := uint8(binary.BigEndian.Uint64(elm[:]) % 255) //fnv is a big-endian hash
			if n > 0 { c := color.RGBA{255, 0, 0, 255} }
			myimage.Set(x, y, c)
		}
	}
	myfile, _ := os.Create("./hash.png")
	png.Encode(myfile, myimage)
}

```

Here is the hash.png for this configuration. It's a big file, too big to attach, but if you zoom in (I attached a zoomed in view), you can visualize how the hash populated the buckets. This populates left to right by bucket bucket[fp,fp,fp,fp] them moves on to the next row, so in the image each line is bucket[fp,fp,fp,fp] , bucket[fp,fp,fp,fp], bucket[fp,fp,fp,fp] ... 12k buckets[fps], then next image row. Hope that makes sense, look at the code. So the current hash is not evenly distributing between rows. One consideration is that fvn is big-endian and the other hash, forget the name, is probably little-endian.


<img width="600" alt="screen shot 2017-01-06 at 9 27 17 am" src="https://cloud.githubusercontent.com/assets/24780673/21724608/5a3a400e-d3f2-11e6-9602-be9a30abfd4d.png">

**Comment by zxdev** [comment]
Okay, I changed the hashfp() and was able to get better load, about 80% before it failed with a "stuffed" alert.

```
cf := cfilter.New(cfilter.FingerprintSize(8), cfilter.BucketSize(4), cfilter.Size(30000000))
```

The "lost" is severely worse (0.11% in first 10MM), so it is a movement issue and things get "lost" with movement of other elements during the kick phase. 

> $ go run cf.go
> 100000000 2m19.873663818s 714930.8676760126 0
> 10000001 4.429207067s 2.257740509204733e+06 **117166** <-- in only the first 10MM


...and running WITHOUT the 10MM break shows in the above code yields a lost of 1.65% of the total hashes entered into the filter (which is about 66% more than an even distribution ratio of x [10MM:100MM] ~ (0.11x10) != 1.65) would be expected if linear. So things are moving all over the table, it is not localized to the first entries.

> $ go run cf.go
> 100000000 2m23.919542418s 694832.6687405455 0
> 100000000 48.275039347s 2.0714638611177297e+06 **1659773**


Here is the hash fill map using a different hash in the hashfp() which allowed a higher load. Note adjusting to 28MM gets a stuffed alert, so the "new" hash isn't ideal either since (per the paper) this should be able to fit 100MM in 106MM sized array. Perhaps finding the flaw in the subsequent movements will resolve everything. So I guess the XOR is not getting the alternate rows correctly or things are just misplaced somehow, maybe it is just an offset error or something... or big/little endian errors... or ???

<img width="936" alt="screen shot 2017-01-06 at 10 37 49 am" src="https://cloud.githubusercontent.com/assets/24780673/21727047/922fc510-d3fc-11e6-8de8-c293ce5a32a6.png">

Where to go from here...

Hopefully this information/analysis help you or someone resolve this "lost" entry XOR issue, since that seems to be the primary issue, or at least track how misplacements occur. Loosing the ability to find entered values after the table is rebalanced/adjusted and existing elements are moved makes this iteration with any level of load unuseable... and I can't put any more time into this at the moment.

**Comment by irfansharif** [comment]
will definitely be looking into this shortly, a bit hard-pressed on time currently (new semester at school and all). thank you again for your initial investigation, I'll follow up on this issue as soon as make headway.

**Comment by zxdev** [comment]
Here is a data dump on 40 inserts. 

j, k, item, hash
x?, i, item, hash

xo = before swap
xa = after swap

4 4 56847afe9799739b b0cb20e340b2bfe6
0 2 3d9677972a3b58ef ba5ee239f5d271fd
9 6 609ba78332428f85 9ab997d540282d37
3 2 ed2534d0b496108a 9c9ddc7b50a4dda1
7 3 4d92ae0b48d32d9c 8382c0e1a3eb0865
1 0 67dc9a302bfc765e 496028c0ed2febf0
3 5 d67bde3d5481cdfa 72969d4a614b7394
6 0 531267aa655aa5ab e76cb288165434a5
1 0 0117ce6bf8b0858d 2948690b223826f1
0 9 8953de5425676ad7 3f9aa3c38aa6513c
8 6 1230f7670b9a26ad 9b04bcb241002812
4 2 566153f124d9e10d 38f53507c55ae815
2 9 935d55ad5a97c389 f488cb2739088d92
7 2 c523190a0f8e4e2b 74d3b68f6e593729
2 8 d3a7ae523e0751f9 360cbfd3d3d6f8f7
6 8 6543159f6a4b2679 14dfbf613622749f
5 3 9a60fc7855d7757c eed92820e545f226
3 6 17629f6cbdf2d907 7f5b820e9a23dad9
1 3 0b5950929256553d 57293c6eda9f565c
0 6 e53150858d0fcacb 3604a8e939e65e3c
8 7 **25ab85eacfe4a24e** 6f9f9d27ab787804
3 6 f38551788ce1ef07 9c4773b5b81b25d1
3 3 16e17e1d733f73ea e3d9c6fb4e13c29c
xo 3 16e17e1d733f73ea e3d9c6fb4e13c29c
xa 2 16e17e1d733f73ea 9c9ddc7b50a4dda1
2 2 23127827bbfa6e4d 1be6893fe1c505e1
4 7 954b307941240574 743696ee2c57535f
3 6 09fc3807a1f595fc 8c395a39b2db38d9
4 0 d9ed94ab80a885f6 6eb0af1bf1487077
4 8 d67a34b1b42e8fcd e2f3995414f9203f
6 2 b68a911fe220eb23 4024675dca67db04
4 7 f7bd2946558645ae 09037e2552b40834
7 6 c351336babaac2e8 47007fd3a86823ac
4 5 c1e79a642ccd77d1 62d8339935203cee
3 9 a502af0f59b2aab7 4f5c3bf92da60c0f
6 2 746995408c79e9ca db62f802b659559c
xo 2 746995408c79e9ca db62f802b659559c
xa 3 746995408c79e9ca 9c9ddc7b50a4dda1
xo 3 746995408c79e9ca 9c9ddc7b50a4dda1
xa 5 746995408c79e9ca 72969d4a614b7394
1 8 312d2793cc997e44 7ae2d0e57dc67782
3 5 fc55eda62f0150bb d01affc1adb22fa2
8 1 b8c59a6f9269ba3a f8111346a4540e60
8 3 081518b62699ee80 f69ebf8ad2f72130
xo 8 081518b62699ee80 f69ebf8ad2f72130
**xa 7 081518b62699ee80 6f9f9d27ab787804
xo 7 081518b62699ee80 6f9f9d27ab787804**
xa 8 081518b62699ee80 09037e2552b40834
xo 8 081518b62699ee80 09037e2552b40834
xa 3 081518b62699ee80 f69ebf8ad2f72130
xo 3 081518b62699ee80 f69ebf8ad2f72130
xa 3 081518b62699ee80 e3d9c6fb4e13c29c
xo 3 081518b62699ee80 e3d9c6fb4e13c29c
xa 6 081518b62699ee80 7f5b820e9a23dad9
xo 6 081518b62699ee80 7f5b820e9a23dad9
xa 8 081518b62699ee80 14dfbf613622749f
xo 8 081518b62699ee80 14dfbf613622749f
xa 6 081518b62699ee80 9b04bcb241002812
xo 6 081518b62699ee80 9b04bcb241002812
xa 1 081518b62699ee80 8c395a39b2db38d9
xo 1 081518b62699ee80 8c395a39b2db38d9
xa 0 081518b62699ee80 2948690b223826f1
3 7 7c7c19c20125ddfc 58215e0777650db7
xo 3 7c7c19c20125ddfc 58215e0777650db7
**xa 2 7c7c19c20125ddfc f69ebf8ad2f72130
xo 2 7c7c19c20125ddfc f69ebf8ad2f72130**
xa 8 7c7c19c20125ddfc db62f802b659559c
xo 8 7c7c19c20125ddfc db62f802b659559c
xa 4 7c7c19c20125ddfc e2f3995414f9203f
xo 4 7c7c19c20125ddfc e2f3995414f9203f
xa 7 7c7c19c20125ddfc 743696ee2c57535f
xo 7 7c7c19c20125ddfc 743696ee2c57535f
xa 0 7c7c19c20125ddfc 6f9f9d27ab787804
xo 0 7c7c19c20125ddfc 6f9f9d27ab787804
xa 2 7c7c19c20125ddfc ba5ee239f5d271fd
xo 2 7c7c19c20125ddfc ba5ee239f5d271fd
xa 3 7c7c19c20125ddfc f69ebf8ad2f72130
xo 3 7c7c19c20125ddfc f69ebf8ad2f72130
xa 2 7c7c19c20125ddfc 9c9ddc7b50a4dda1
xo 2 7c7c19c20125ddfc 9c9ddc7b50a4dda1
xa 9 7c7c19c20125ddfc f488cb2739088d92
4 0 cca872608af9e370 58bce4cc734617e2
xo 0 cca872608af9e370 58bce4cc734617e2
xa 9 cca872608af9e370 3f9aa3c38aa6513c
0 6f9f9d27ab787804 58bce4cc734617e2 3604a8e939e65e3c 2948690b223826f1 
1 496028c0ed2febf0 8c395a39b2db38d9 57293c6eda9f565c 7ae2d0e57dc67782 
2 9c9ddc7b50a4dda1 360cbfd3d3d6f8f7 ba5ee239f5d271fd 1be6893fe1c505e1 
3 58215e0777650db7 f69ebf8ad2f72130 e3d9c6fb4e13c29c 9c4773b5b81b25d1 
4 b0cb20e340b2bfe6 38f53507c55ae815 e2f3995414f9203f 6eb0af1bf1487077 
5 eed92820e545f226 62d8339935203cee 72969d4a614b7394 d01affc1adb22fa2 
6 e76cb288165434a5 7f5b820e9a23dad9 9b04bcb241002812 4024675dca67db04 
7 8382c0e1a3eb0865 74d3b68f6e593729 743696ee2c57535f 47007fd3a86823ac 
8 14dfbf613622749f 09037e2552b40834 db62f802b659559c f8111346a4540e60 
9 9ab997d540282d37 4f5c3bf92da60c0f f488cb2739088d92 3f9aa3c38aa6513c 
41 473.597µs 86537.69033015185 0
21 **25ab85eacfe4a24e** missing
26 09fc3807a1f595fc missing
30 f7bd2946558645ae missing
34 746995408c79e9ca missing

25ab85eacfe4a24e, 21st entry, hashes to 6f9f9d27ab787804 which should be in 8 or 7, so how did it wind up in row 0 with only one reported move...

...anyway, I've proven the issue is in the movement.

**Comment by zxdev** [comment]
![screen shot 2017-01-10 at 6 23 39 pm](https://cloud.githubusercontent.com/assets/24780673/21831582/fd3fbc80-d761-11e6-99ad-804e221babf5.png)

I solved the problem, above is 97% load ... but I had to write my own filter (it was just easier to write an entirely new skeleton).

Basically here's what you need to do to resolve this in your version.

1. be aware of the order of operations with xor and mod to get proper bucket selection; same kind of thing with that ^= problem before
2. you need cyclic detection, not just a kicker; if you reread the paper it only mentions this in passing and I missed it the first few times through the paper... write a remodeler
3. optionally, you can simplify the indexer hash to increase performance; reread the paper 
4. optionally, discovered that you can use more indexes and/or more buckets to effect placement options and ultimately the load; there is a relationship between lookup performance and insert performance, tune for your needs

Applying the above to my skeleton, I was able to get the following performance metric results using the 100MM sample data, using 4 buckets, fingerprint size of 8, and 2 indexes (basically same settings that I used when I posted/created this issue). 

120MM container, 100MM records, **83% load**, 2.4MM ops/sec insert, 2.7MM ops/sec lookup
> 120000000 100000000 42.457445103 2.355299502727142e+06 83.33333333333334
> 100000000 37.183076798 2.689395492686905e+06

103MM container, 100MM records, **97% load**, 847K ops/sec insert, 2.7MM ops/sec lookup
>103000000 100000000 118.057337027 847046.039437036 97.0873786407767
>100000000 38.985390071 2.6650634518015934e+06

The same 103MM container, but with **4 indices** this time yields 2.5x more insert performance with only 10% lookup performance penalty and still yields 97% load value. This happens because more placement options with fewer remodel events happening.

103MM container, 100MM records, 97% load, **2.13MM ops/sec insert**, 2.42MM ops/sec lookup
>103000000 100000000 46.82338113 2.1356851409716825e+06 97.0873786407767
>100000000 41.243313793 2.4246354169096304e+06

102MM container, 100MM records, 98% load, using 4 indices, 1.86MM ops/sec insert, 2.22MM ops/sec lookup
>102000000 100000000 53.5599897 1.867065323081785e+06 98.0392156862745
>100000000 44.994287322 2.222504353296009e+06

There is probably some GO overhead included in the 1.6GB  running memory footprint I am seeing. Dialing the fingerprint size back to 2 means 100MM items fits in about 400MB which is what I was looking for, but still more than the 4 billion items in 192 MB the paper talks about.

Depending on your data size, buckets, and indices (and patience) -- you can get 100% filter load. I did this several times with smaller sample sizes, eg 10k, 100k, 1MM. Staying with 2 indices, and 8 buckets will also generate yields of 98%+ load factors.


Cheers!

**Comment by irfansharif** [comment]
re-opening this issue to track it's progress here.

**Comment by irfansharif** [comment]
No longer maintaining this.
