### ISSUE TITLE
Italian spelling mistake

### ISSUE THREAD

**Issue by PirosB3** [irfansharif/cfilter#3]
Hi!

Thanks for this amazing package, looking forward to reading the source!
I'm not sure if this was done on purpose, but "good morning" in Italian is b**u**ongiorno. Let me know if you want me to make a PR with the typo fix!

Thanks again
Daniel

**Comment by irfansharif** [comment]
haha, definitely not on purpose no but thank you for pointing it out! yes please do, it's all over in the `cfilter_test.go` file too.
