### ISSUE TITLE
feature request: add a way to persist/load the filter

### ISSUE THREAD

**Issue by bystones** [irfansharif/cfilter#5]
I would like to persist the filter via something like io.WriterTo and read it back with io.ReaderFrom to let it suvive application restarts.

**Comment by donatj** [comment]
I second this. At the very least make the things public that would need to be public for this to easily JSON encode/decode.

**Comment by tj** [comment]
👍  need this as well, I'll send a PR for Marshal/Unmarshal binary at some point

**Comment by irfansharif** [comment]
@tj: I'm curious as to how you managed to find this project, shot up in popularity in the last few hours..

**Comment by tj** [comment]
Just godoc :D

**Comment by irfansharif** [comment]
@tj: you probably get this all the time but I've been following your work since your Node.js days, it's very cool what you're doing with Apex now!

**Comment by tj** [comment]
Thanks man!

**Comment by irfansharif** [comment]
No longer maintaining this.

**Comment by donatj** [comment]
> No longer maintaining this.

Sad day, I use this on a bunch of projects.
