### ISSUE TITLE
Algorithmic Improvements for Fast Concurrent Cuckoo Hashing

### ISSUE THREAD

**Issue by irfansharif** [irfansharif/cfilter#7]
The ideas described in the paper [here](https://www.cs.princeton.edu/~mfreed/docs/cuckoo-eurosys14.pdf) are pretty interesting and doable.

**Comment by resilva87** [comment]
Hi

@irfansharif The link you posted has moved :(. There's no reference at all.

**Comment by irfansharif** [comment]
hey @resilva87, thanks for pointing it out. updated now.

**Comment by irfansharif** [comment]
No longer maintaining this.
